version: 2
updates:

  # Maintain dependencies for Docker Images
  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "kind/dependabot"
    reviewers:
      - "k3s-io/k3s-dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "kind/dependabot"
    reviewers:
      - "k3s-io/k3s-dev"
    schedule:
      interval: "cron"
      cronjob: "0 0 1 */3 *" # Every 3rd month
    groups:
      action-deps:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

