apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deploy-cluster-scoped.yaml
- manifests/deploy-namespaced.yaml
images:
- name: rancher/helm-controller
  newTag: v0.12.1
