apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  labels:
    app: helm-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-controller
  template:
    metadata:
      labels:
        app: helm-controller
    spec:
      containers:
        - name: helm-controller
          image: rancher/helm-controller
          command: ["helm-controller"]
          args: ["--threads", "2", "--namespace", "kube-system"]