#!/bin/bash

ARCH=${ARCH:-$(go env GOHOSTARCH)}
SUFFIX="-${ARCH}"

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

# For docker image
TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

# If tag contains dirty, set to dev
if echo $TAG | grep -q dirty; then
    TAG=dev
fi
