name: Build and Test
on:
  push:
    branches:
      - master
  pull_request: {}

permissions:
  contents: read

jobs:
  unit: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'

      - name: Unit Test
        run: go test ./pkg/... -cover -tags=test
  
  ci:
    runs-on: ubuntu-latest
    env:
      ARCH: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'

      - name: Build binary
        run: make build
    
      - name: Validate
        run: make validate
      
      - name: Package
        run: make package

      - name: E2E Test
        run: ./scripts/e2e

  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Build arm64 binary
        run: docker buildx build --platform linux/arm64 --target binary --output type=local,dest=. .

  build-riscv64:
    if: github.repository_owner == 'k3s-io'
    runs-on: cncf-ubuntu-8-32-x86
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Build riscv64 binary
        run: docker buildx build --platform linux/riscv64 --target binary --output type=local,dest=. .
