name: Build and Test
on:
  push:
    branches:
      - master
  pull_request: {}

permissions:
  contents: read

jobs:
  unit: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'

      - name: Unit Test
        run: go test ./pkg/... -cover -tags=test
  
  ci:
    runs-on: ubuntu-latest
    env:
      ARCH: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'

      - name: Build binary
        run: make build
    
      - name: Validate
        run: make validate
      
      - name: Package
        run: make package

      - name: E2E Test
        run: ./scripts/e2e

  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build arm64 binary
        run: docker buildx build --platform linux/arm64 --target binary --output type=local,dest=. .

  build-riscv64:
    if: github.repository_owner == 'k3s-io'
    runs-on: cncf-ubuntu-8-32-x86
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build riscv64 binary
        run: docker buildx build --platform linux/riscv64 --target binary --output type=local,dest=. .
