name: Build and Test
on:
  push:
    branches:
      - master
  pull_request: {}

permissions:
  contents: read

jobs:
  unit: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Unit Test
        run: go test ./pkg/... -cover -tags=test
  
  ci:
    runs-on: ubuntu-latest
    env:
      ARCH: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary
        run: make build
    
      - name: Validate
        run: make validate
      
      - name: Package
        run: make package

      - name: E2E Test
        run: ./scripts/e2e